on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: Publish

jobs:
  build-and-deploy-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      - name: Generate build ID
        id: prep
        run: |
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${sha}-${ts}"

      - name: 'Build and push Linux image'
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -f Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/azure-devops-agent:linux-pr-${{github.event.number}}-${{ steps.prep.outputs.BUILD_ID }} .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/azure-devops-agent:linux-pr-${{github.event.number}}-${{ steps.prep.outputs.BUILD_ID }}
        if: startsWith(github.ref, 'refs/pull')
      - run: |
          docker build -f Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/azure-devops-agent:linux-prod-${{ steps.prep.outputs.BUILD_ID }} .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/azure-devops-agent:linux-prod-${{ steps.prep.outputs.BUILD_ID }}
        if: github.ref == 'refs/heads/main'

  build-and-deploy-windows:
    runs-on: windows-2022
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      - name: Generate build ID
        id: prep
        run: |
          $sha = "${{ github.sha }}".Substring(0, 8)
          $ts = [int][double]::Parse((Get-Date -UFormat %s))
          echo "::set-output name=BUILD_ID::${sha}-${ts}"

      - name: 'Build and push Windows image'
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -f Dockerfile.windows -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/azure-devops-agent:windows-pr-${{github.event.number}}-${{ steps.prep.outputs.BUILD_ID }} .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/azure-devops-agent:windows-pr-${{github.event.number}}-${{ steps.prep.outputs.BUILD_ID }}
        if: startsWith(github.ref, 'refs/pull')
      - run: |
          docker build -f Dockerfile.windows -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/azure-devops-agent:windows-prod-${{ steps.prep.outputs.BUILD_ID }} .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/azure-devops-agent:windows-prod-${{ steps.prep.outputs.BUILD_ID }}
        if: github.ref == 'refs/heads/main'