on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: Publish

jobs:
  build-and-deploy-linux:
    name: Build and push Linux container
    uses: hmcts/.github/.github/workflows/container-build-and-push.yaml@feat/docker-reusable-workflow
    with:
      image-name: azure-devops-agent
      dockerfile: Dockerfile
      platforms: linux/amd64
      image-tags: |
        type=ref,event=branch
        type=ref,event=pr
        type=sha
      push: true    
    secrets:
      REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

  build-and-deploy-windows:
    name: Build and push Windows container
    uses: hmcts/.github/.github/workflows/container-build-and-push.yaml@feat/docker-reusable-workflow
    with:
      image-name: azure-devops-agent-windows
      dockerfile: Dockerfile.windows
      platforms: windows/amd64
      image-tags: |
        type=ref,event=branch
        type=ref,event=pr
        type=sha
      push: true
    secrets:
      REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
