on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Publish

jobs:
  build-and-deploy-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - name: Generate build ID
        id: prep
        run: |
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "BUILD_ID=${sha}-${ts}" >> $GITHUB_OUTPUT

      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: b354d443-d632-4d61-8ee8-2abc2c7baf23 # DTS Shared GitHub Actions ACR Publisher 1
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
          allow-no-subscriptions: true

      - name: 'ACR Login'
        run: |
          az acr login --name hmctsprod

      # HMCTSPROD ACR
      - name: 'Build and push PR image to HMCTSPROD'
        if: startsWith(github.ref, 'refs/pull')
        run: |
          docker build -f Dockerfile -t hmctsprod.azurecr.io/azure-devops-agent:pr-${{github.event.number}}-${{ steps.prep.outputs.BUILD_ID }} .
          docker push hmctsprod.azurecr.io/azure-devops-agent:pr-${{github.event.number}}-${{ steps.prep.outputs.BUILD_ID }}

      - name: 'Build and push prod image to HMCTSPROD'
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -f Dockerfile -t hmctsprod.azurecr.io/azure-devops-agent:prod-${{ steps.prep.outputs.BUILD_ID }} .
          docker push hmctsprod.azurecr.io/azure-devops-agent:prod-${{ steps.prep.outputs.BUILD_ID }}

      # HMCTSPUBLIC ACR - to be deprecated post migration to hmctsprod

      - name: 'Build and push Linux image'
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -f Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/azure-devops-agent:pr-${{github.event.number}}-${{ steps.prep.outputs.BUILD_ID }} .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/azure-devops-agent:pr-${{github.event.number}}-${{ steps.prep.outputs.BUILD_ID }}
        if: startsWith(github.ref, 'refs/pull')
      - run: |
          docker build -f Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/azure-devops-agent:prod-${{ steps.prep.outputs.BUILD_ID }} .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/azure-devops-agent:prod-${{ steps.prep.outputs.BUILD_ID }}
        if: github.ref == 'refs/heads/main'

  build-and-deploy-windows:
    runs-on: windows-2025
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - name: Generate build ID
        id: prep
        run: |
          $sha = "${{ github.sha }}".Substring(0, 8)
          $ts = [int][double]::Parse((Get-Date -UFormat %s))
          echo "BUILD_ID=${sha}-${ts}" >> $env:GITHUB_OUTPUT

      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: b354d443-d632-4d61-8ee8-2abc2c7baf23 # DTS Shared GitHub Actions ACR Publisher 1
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
          allow-no-subscriptions: true

      - name: 'ACR Login'
        run: |
          az acr login --name hmctsprod

      # HMCTSPROD ACR
      - name: 'Build and push PR image to HMCTSPROD'
        if: startsWith(github.ref, 'refs/pull')
        run: |
          docker build -f Dockerfile.windows -t hmctsprod.azurecr.io/azure-devops-agent-windows:pr-${{github.event.number}}-${{ steps.prep.outputs.BUILD_ID }} .
          docker push hmctsprod.azurecr.io/azure-devops-agent-windows:pr-${{github.event.number}}-${{ steps.prep.outputs.BUILD_ID }}

      - name: 'Build and push prod image to HMCTSPROD'
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -f Dockerfile.windows -t hmctsprod.azurecr.io/azure-devops-agent-windows:prod-${{ steps.prep.outputs.BUILD_ID }} .
          docker push hmctsprod.azurecr.io/azure-devops-agent-windows:prod-${{ steps.prep.outputs.BUILD_ID }}

      # HMCTSPUBLIC ACR - to be deprecated post migration to hmctsprod

      - name: 'Build and push Windows image'
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push PR image
        run: |
          docker build -f Dockerfile.windows -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/azure-devops-agent-windows:pr-${{github.event.number}}-${{ steps.prep.outputs.BUILD_ID }} .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/azure-devops-agent-windows:pr-${{github.event.number}}-${{ steps.prep.outputs.BUILD_ID }}
        if: startsWith(github.ref, 'refs/pull')
      - name: Build and push prod image
        run: |
          docker build -f Dockerfile.windows -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/azure-devops-agent-windows:prod-${{ steps.prep.outputs.BUILD_ID }} .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/azure-devops-agent-windows:prod-${{ steps.prep.outputs.BUILD_ID }}
        if: github.ref == 'refs/heads/main'